boxlog/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^', include('main.urls')),
    url(r'^admin/', admin.site.urls),
]

main/urls.py
from django.conf.urls import url

from . import views

app_name = 'main'
urlpatterns = [
    url(r'^$', views.index),
    url(r'^id/(\w+)/$', views.viewBox),
    url(r'^updateBox/$', views.updateBox),
    url(r'^addItem/$', views.addItem),
    url(r'^label/(\w+)/$', views.genLabel),
    #url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    #url(r'^$', views.IndexView.as_view(), name='index'),
    #url(r'^recent/$', views.RecentView.as_view(), name='recent'),
    #url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    #url(r'^(?P<box_id>[0-9]+)/vote/$', views.vote, name='vote'),
    
]

polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

main/models.py
from __future__ import unicode_literals
import datetime
from django.db import models
from django.utils import timezone



class Box(models.Model):
    box_id = models.CharField(max_length=200)
    box_label = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.box_label
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Item(models.Model):
    box = models.ForeignKey(Box, on_delete=models.CASCADE)
    item_name = models.CharField(max_length=200)
    item_description = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.item_name
 

polls/models.py
from __future__ import unicode_literals
import datetime
from django.db import models
from django.utils import timezone



class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

main/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.template import loader
from django.http import Http404
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
#from .forms import NameForm
from django.utils import timezone
from random import randint

from .models import Box, Item


def encodeID(num, alphabet="23456789abcdefghijkmnpqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ"):
    if num == 0:
        return alphabet[0]
    arr = []
    base = len(alphabet)
    while num:
        num, rem = divmod(num, base)
        arr.append(alphabet[rem])
    arr.reverse()
    return ''.join(arr)


def index(request):
    if request.method == 'POST':
            boxLabel = request.POST['boxLabel']
            
            #box = Box.objects.filter(box_id=boxLabel)[0]
            #box.item_set.create(item_name='Not much', votes=0)
            base56ID = encodeID(randint(10000000, 99999999))
            b = Box(box_id=base56ID, box_label=boxLabel, pub_date=timezone.now())
            b.save()

            #box = Box.objects.filter(box_id=request.POST['boxLabel'])[0]
            #test_label = box.box_label
            redirectURL = 'id/' + base56ID
            return HttpResponseRedirect(redirectURL)
            #return HttpResponse(base56ID)
    else:
        return render(request, 'main/index.html')
    
def viewBox(request, urlhash):
    box = Box.objects.filter(box_id=urlhash)[0]
    context_dict = {}
    context_dict['box'] = box
    return render(request, 'main/detail.html', context_dict)
    
def updateBox(request):
    if request.method == 'POST':
            boxID = request.POST['boxID']
            box = Box.objects.filter(box_id=request.POST['boxID'])[0]

            counter = 1;
            for item in box.item_set.all():
                item.item_name = request.POST['item' + str(counter)]
                item.item_description = request.POST['description' + str(counter)]
                item.save()
                counter += 1
            #test_label = box.box_label
            redirectURL = '/id/' + box.box_id + '/'
            return HttpResponseRedirect(redirectURL)
            #return HttpResponse(box.box_id)
    else:
        return HttpResponseRedirect('/')
        
def addItem(request):
    if request.method == 'POST':
            boxID = request.POST['boxID']
            box = Box.objects.filter(box_id=request.POST['boxID'])[0]
            box.item_set.create(item_name='', item_description='')
            #test_label = box.box_label
            redirectURL = '/id/' + box.box_id + '/'
            return HttpResponseRedirect(redirectURL)
            #return HttpResponse(box.box_id)
    else:
        return HttpResponseRedirect('/')
        
def genLabel(request, urlhash):
    box = Box.objects.filter(box_id=urlhash)[0]
    context_dict = {}
    context_dict['box'] = box
    return render(request, 'main/label.html', context_dict)
        
   
#class IndexView(generic.View):
#    template_name = 'main/index.html'

#class RecentView(generic.ListView):
#    template_name = 'main/recent.html'
#    context_object_name = 'latest_box_list'

#    def get_queryset(self):
#        """Return published boxes."""
#        return Box.objects.all()

#class DetailView(generic.DetailView):
#    model = Box
#    template_name = 'main/detail.html'

#class DetailView(generic.DetailView):
#    model = Box
#    template_name = 'main/detail.html'
#    context_object_name = 'box'

#    def get_queryset(self):
#        """Return box by box_id"""
#        return Box.objects.filter(box_id=urlhash)

#class ResultsView(generic.DetailView):
#    model = Box
#    template_name = 'main/results.html'

#def vote(request, box_id):
#    box = get_object_or_404(Box, pk=box_id)
#    try:
#        selected_choice = box.item_set.get(pk=request.POST['choice'])
#    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
#        return render(request, 'main/detail.html', {
#            'box': box,
#            'error_message': "You didn't select a choice.",
#        })
#    else:
#        selected_choice.votes += 1
#        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
#        return HttpResponseRedirect(reverse('main:results', args=(box.id,)))

polls/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.template import loader
from django.http import Http404
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic

from .models import Choice, Question


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

main/templates/main/detail.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'main/style.css' %}" />
<title>Boxlog - {{ box.box_label }}</title>

<div id="topbar">
 <h1>{{ box.box_label }}</h1> 
     <img id="imgQR">
</div>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<table>
    <tr>
        <th>Item</th>
        <th>Description</th>
    </tr>
   {% for item in box.item_set.all %}
    <tr>
    <td id="itemTD{{ forloop.counter }}" class="item-col item{{ forloop.counter }}" contenteditable="true"  onkeyup="updateForm(this)">{{ item.item_name }}</td>
    <td id="descTD{{ forloop.counter }}" class="desc-col description{{ forloop.counter }}" contenteditable="true"  onkeyup="updateForm(this)">{{ item.item_description }}</td>
    </tr>
    {% endfor %} 
</table>


<form id="addForm" action="/addItem/" method="post">
{% csrf_token %}
<input type="hidden" name="boxID" value="{{ box.box_id }}" />

</form>

<form id="updateForm" action="/updateBox/" method="post">
{% csrf_token %}
<input type="hidden" name="boxID" value="{{ box.box_id }}" />
<input type="hidden" name="numItems" value="{{ box.item_set.count }}" />
{% for item in box.item_set.all %}
    <input type="hidden" name="item{{ forloop.counter }}" id="item{{ forloop.counter }}" value="{{ item.item_name }}" />
    <input type="hidden" name="description{{ forloop.counter }}" id="description{{ forloop.counter }}" value="{{ item.item_description }}" />
{% endfor %}

</form>
<div id="ctrlDiv">
<a class="btn" href="https://boxlog-mlindysay.c9users.io/label/{{ box.box_id }}/">Generate Box Label</a>
<input form="addForm" class="btn" type="submit" value="Add Item" />
<input form="updateForm" class="btn" type="submit" value="Save Changes" />  
</div>

<script>
    var qrcode = "https://chart.googleapis.com/chart?cht=qr&chs=150x150&choe=UTF-8&chld=H&chl=https://boxlog-mlindysay.c9users.io/id/{{ box.box_id }}/";
    imgQR = document.querySelector("#imgQR");
    imgQR.src = qrcode;
    
    function updateForm(cell) {
        var input2Update = "#" + cell.classList[1];
        document.querySelector(input2Update).value = cell.innerHTML;
    }
</script>

main/templates/main/index.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'main/style.css' %}" />
<title>Boxlog - Create a new box!</title>

<div id="startForm">
 <h1>Boxlog</h1>   
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<p>Type in a label for your box.</p>


<form id="createBox" action="/" method="post">
{% csrf_token %}
    <input type="text" name="boxLabel"  value="" />
    <input class="btn" type="submit" value="Create Box" />
</form>
</div>

main/templates/main/label.html
<title>Boxlog - {{ box.box_label }}</title>

<div style="border-style: dashed; display: inline-block;">
 <h1 style="text-align: center; margin-left: 20px; margin-right: 20px;">{{ box.box_label }}</h1> 
     <img id="imgQR" style="display: block; margin: 0 auto;">
</div>

<p style="text-align: center; margin-top: 30px;">Print this label out, cut it out, and tape it to your box.  Scan the QR code to view/update your box's contents.</p>

<script>
    var qrcode = "https://chart.googleapis.com/chart?cht=qr&chs=150x150&choe=UTF-8&chld=H&chl=https://boxlog-mlindysay.c9users.io/id/{{ box.box_id }}/";
    imgQR = document.querySelector("#imgQR");
    imgQR.src = qrcode;
</script>

main/templates/main/recent.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'main/style.css' %}" />

{% if latest_box_list %}
    <ul>
    {% for box in latest_box_list %}
        <li><a href="{% url 'main:detail' box.id %}">{{ box.box_label }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No boxes have been created.</p>
{% endif %}

main/templates/main/results.html
<h1>{{ box.box_label }}</h1>

<ul>
{% for item in box.item_set.all %}
    <li>{{ item.item_name }} -- {{ item.votes }} vote{{ item.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'main:detail' box.id %}">Vote again?</a>

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

polls/templates/polls/index.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>